import type {
  AchievementDefinition,
  ActivityDefinition,
  RumorDefinition,
} from "@/types/game";

/** Campus activities are content data; the runner only knows their game type. */
export const activities: ActivityDefinition[] = [
  {
    id: "source-sleuth",
    title: "Source Sleuth",
    domain: "ACADEMICS",
    subtitle: "Library lab",
    description: "Sort a promising source from a loud one before your study group meets.",
    gameType: "choice",
    rewardXp: 30,
    locationId: "library",
    rounds: [
      {
        prompt: "Which clue makes a source the best starting point for a research paper?",
        options: ["A viral headline", "A cited peer-reviewed study", "An anonymous comment"],
        correctIndex: 1,
        explanation: "A cited peer-reviewed study gives you evidence and a trail to evaluate.",
      },
    ],
    tags: ["research", "study"],
  },
  {
    id: "debug-dash",
    title: "Debug Dash",
    domain: "TECH",
    subtitle: "ICS makers' corner",
    description: "Spot the tiny mismatch and keep the prototype moving.",
    gameType: "choice",
    rewardXp: 30,
    locationId: "ics",
    specialty: "COMPUTING",
    rounds: [
      {
        prompt: "The button never responds. What is the most useful first move?",
        options: ["Rewrite everything", "Read the console and reproduce the issue", "Blame the network"],
        correctIndex: 1,
        explanation: "A small reproducible observation is faster and safer than guessing.",
      },
    ],
    tags: ["build", "logic"],
  },
  {
    id: "power-path",
    title: "Power Path",
    domain: "TECH",
    subtitle: "Engineering studio",
    description: "Route a safe signal through a simple campus sensor board.",
    gameType: "choice",
    rewardXp: 35,
    specialty: "ENGINEERING",
    rounds: [{
      prompt: "The signal starts at the battery and must reach the lamp. Which order is valid?",
      options: ["Battery → switch → lamp", "Lamp → battery → switch", "Switch → lamp → battery"],
      correctIndex: 0,
      explanation: "A closed switch between the source and lamp completes the abstract circuit.",
    }],
    tags: ["engineering", "routing"],
  },
  {
    id: "logic-router",
    title: "Logic Router",
    domain: "TECH",
    subtitle: "Makers' corner",
    description: "Choose the valid order for a tiny decision router. No coding background required.",
    gameType: "choice",
    rewardXp: 35,
    specialty: "COMPUTING",
    rounds: [{
      prompt: "A door opens only when the badge is valid AND the safety check passes. What should the router do?",
      options: ["Open when either input is true", "Open only when both inputs are true", "Open when both inputs are false"],
      correctIndex: 1,
      explanation: "AND requires both conditions to be true.",
    }],
    tags: ["computing", "logic"],
  },
  {
    id: "campus-budget",
    title: "Campus Budget",
    domain: "LEADERSHIP",
    subtitle: "Student council desk",
    description: "Balance a small fictional event budget without sacrificing access.",
    gameType: "choice",
    rewardXp: 35,
    specialty: "BUSINESS_FINANCE",
    rounds: [{
      prompt: "A club has a fixed budget. Which plan protects access and still leaves a safety buffer?",
      options: ["Spend everything on one headline item", "Choose essentials, compare quotes, and keep a buffer", "Cancel support for first-time attendees"],
      correctIndex: 1,
      explanation: "A buffer and transparent priorities make the plan resilient.",
    }],
    tags: ["business", "planning"],
  },
  {
    id: "process-order",
    title: "Process Order",
    domain: "ACADEMICS",
    subtitle: "Life science noticeboard",
    description: "Put a harmless educational observation process in a sensible order.",
    gameType: "choice",
    rewardXp: 35,
    specialty: "LIFE_SCIENCE",
    rounds: [{
      prompt: "Which sequence best describes a careful classroom observation?",
      options: ["Record → observe → ask a question", "Ask a question → observe → record", "Conclude → observe → record"],
      correctIndex: 1,
      explanation: "A question guides observation, and records preserve what was seen.",
    }],
    tags: ["science", "sequence"],
  },
  {
    id: "evidence-file",
    title: "Evidence File",
    domain: "COMMUNITY",
    subtitle: "Civic desk",
    description: "Separate a claim from evidence before a fictional campus discussion.",
    gameType: "choice",
    rewardXp: 35,
    specialty: "LAW_SOCIETY",
    rounds: [{
      prompt: "Which item is evidence rather than an assumption?",
      options: ["A dated event notice", "Everyone probably agrees", "The story feels true"],
      correctIndex: 0,
      explanation: "A dated notice can be checked; the other statements add unsupported assumptions.",
    }],
    tags: ["society", "reasoning"],
  },
  {
    id: "cipher-note",
    title: "Cipher Note",
    domain: "CREATIVE",
    subtitle: "Humanities club table",
    description: "Decode a short fictional note using the clue card provided.",
    gameType: "choice",
    rewardXp: 35,
    specialty: "LANGUAGE_HUMANITIES",
    rounds: [{
      prompt: "The clue says SHIFT EACH LETTER ONE STEP BACK. What does DBNQVT become?",
      options: ["CAMPUS", "DEPART", "CIRCLE"],
      correctIndex: 0,
      explanation: "Moving each letter back one position reveals CAMPUS.",
    }],
    tags: ["language", "cipher"],
  },
  {
    id: "observation-memo",
    title: "Observation Memo",
    domain: "COMMUNITY",
    subtitle: "Explorer route",
    description: "Notice what is present, record it carefully, and avoid inventing details.",
    gameType: "choice",
    rewardXp: 25,
    specialty: "GENERAL",
    rounds: [{
      prompt: "What makes an exploration note most useful?",
      options: ["A precise description of what you actually saw", "A dramatic detail added later", "A copied rumor with no source"],
      correctIndex: 0,
      explanation: "Careful observation helps other explorers verify a discovery.",
    }],
    tags: ["exploration", "observation"],
  },
  {
    id: "club-pitch",
    title: "Club Pitch",
    domain: "LEADERSHIP",
    subtitle: "Student life",
    description: "Make a new club sound welcoming, concrete, and ready for its first member.",
    gameType: "choice",
    rewardXp: 30,
    rounds: [
      {
        prompt: "Which opening best invites a first-time participant?",
        options: ["Experts only", "Bring one idea; we will build it together", "No questions during the meeting"],
        correctIndex: 1,
        explanation: "Clear, low-pressure invitations make participation easier.",
      },
    ],
    tags: ["clubs", "people"],
  },
  {
    id: "poster-remix",
    title: "Poster Remix",
    domain: "CREATIVE",
    subtitle: "Design studio",
    description: "Give an event poster a clear message without losing its personality.",
    gameType: "choice",
    rewardXp: 30,
    rounds: [
      {
        prompt: "What should a useful event poster make obvious first?",
        options: ["The event name, date, and place", "Every possible font choice", "A wall of tiny text"],
        correctIndex: 0,
        explanation: "A clear hierarchy helps people understand and act at a glance.",
      },
    ],
    tags: ["design", "expression"],
  },
  {
    id: "reset-breath",
    title: "Reset Breath",
    domain: "WELLBEING",
    subtitle: "Quiet corner",
    description: "Choose a small, kind next step when a busy day starts to feel too loud.",
    gameType: "choice",
    rewardXp: 25,
    rounds: [
      {
        prompt: "A classmate feels overwhelmed. What is a supportive first response?",
        options: ["Listen and ask what support would help", "Share their story publicly", "Tell them to ignore it"],
        correctIndex: 0,
        explanation: "Listening respectfully keeps agency and privacy with the person asking for help.",
      },
    ],
    tags: ["care", "balance"],
  },
  {
    id: "three-point-timing",
    title: "Three-Point Timing",
    domain: "SPORTS",
    subtitle: "Indoor court",
    description: "Stop the moving meter inside the sweet spot to sink a clean shot.",
    gameType: "timing",
    rewardXp: 40,
    rounds: [{ prompt: "Stop the meter in the gold zone.", explanation: "A steady release beats a rushed one." }],
    tags: ["arcade", "basketball"],
  },
  {
    id: "cricket-boundary-timing",
    title: "Cricket Boundary Timing",
    domain: "SPORTS",
    subtitle: "Practice nets",
    description: "Meet the moving ball in the sweet spot and time a clean boundary.",
    gameType: "timing",
    rewardXp: 45,
    rounds: [{ prompt: "Release the bat inside the gold timing zone.", explanation: "A calm eye and a clean contact make the difference." }],
    tags: ["arcade", "cricket", "timing"],
  },
  {
    id: "futsal-penalty",
    title: "Futsal Penalty",
    domain: "SPORTS",
    subtitle: "Five-a-side pitch",
    description: "Pick a corner, watch the keeper, and take your penalty.",
    gameType: "penalty",
    rewardXp: 40,
    rounds: [{ prompt: "Choose a corner before the keeper commits.", explanation: "Mixing up your approach keeps the keeper guessing." }],
    tags: ["arcade", "futsal"],
  },
  {
    id: "table-tennis-reaction",
    title: "Table Tennis Reaction",
    domain: "SPORTS",
    subtitle: "Recreation room",
    description: "Wait for the serve signal, then react as quickly as you can.",
    gameType: "reaction",
    rewardXp: 40,
    rounds: [{ prompt: "Wait for GO, then return the serve.", explanation: "Anticipation is useful; jumping the signal is a fault." }],
    tags: ["arcade", "reaction"],
  },
  {
    id: "midnight-stairwell",
    title: "The Midnight Stairwell",
    domain: "COMMUNITY",
    subtitle: "Hidden discovery",
    description: "A whispered route, a kind custodian, and one campus story that is not on the map.",
    gameType: "choice",
    rewardXp: 20,
    hidden: true,
    rounds: [
      {
        prompt: "The rumor points to a closed stairwell. What should an explorer do?",
        options: ["Respect the boundary and ask the staff for the public story", "Climb in alone", "Post the location online"],
        correctIndex: 0,
        explanation: "Discovery is better when it remains safe, accessible, and respectful.",
      },
    ],
    tags: ["rumor", "npc"],
  },
];

export const achievements: AchievementDefinition[] = [
  { id: "first-activity", title: "First Bell", description: "Complete your first campus activity.", icon: "✦" },
  { id: "activity-explorer", title: "Campus Circuit", description: "Complete activities in three different domains.", icon: "◈" },
  { id: "sports-ace", title: "Sports Arcade Ace", description: "Score 80 or higher in any sports activity.", icon: "★" },
  { id: "rumor-keeper", title: "Rumor Keeper", description: "Uncover the Midnight Stairwell story.", icon: "☾" },
];

export const rumors: RumorDefinition[] = [
  {
    id: "midnight-stairwell",
    title: "The Midnight Stairwell",
    npc: "Mina, the night-shift custodian",
    text: "There is a stairwell with the best echo on campus—but it is only a story, not an invitation to enter closed areas.",
    hint: "Ask a staff member about the old Block B rehearsal room.",
  },
  {
    id: "rooftop-garden",
    title: "The Rooftop Garden",
    npc: "Rafi from the gardening club",
    text: "A few planters appear after every monsoon. Students leave a note when the first new leaf opens.",
    hint: "Look for a public green-space noticeboard during daylight.",
  },
];

export function activityById(id: string) {
  return activities.find((activity) => activity.id === id);
}
